---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
Cell In[3], line 2
      1 # 실행
----> 2 collect_selected_series(
      3     txt_path='250407_sarima_selected_pqr_seasonal.txt',
      4     label='seasonal',
      5     output_path='250407_sarima_selected_seasonal.csv'
      6 )
      8 collect_selected_series(
      9     txt_path='250407_sarima_selected_pqr_trend.txt',
     10     label='trend',
     11     output_path='250407_sarima_selected_trend.csv'
     12 )

Cell In[2], line 15
     13 def collect_selected_series(txt_path, label, output_path):
     14     root = f'sarima_forecast_results/{label}'
---> 15     selected = load_selected_variables(txt_path, label)
     17     df_all = pd.DataFrame()
     19     for var_name, full_col_name in selected:

Cell In[2], line 4
      2 selected = []
      3 with open(txt_path, 'r') as f:
----> 4     for line in f:
      5         line = line.strip()
      6         if line:

UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 2112: illegal multibyte sequence
